service: products-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-south-1
  stage: dev

functions:
  hello:
    handler: handler.getProductsList
    events:
      - httpApi:
          path: /products
          method: get