service: authorization-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-south-1
  stage: dev
  apiGateway:
    minimumCompressionSize: 1024

functions:
  basicAuthorizer:
    handler: handlers/handler.basicAuthorizer
